name: Claude Auto Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Automatic PR Review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "90"
          max_turns: "20"
          direct_prompt: |
            Please review this pull request and provide comprehensive feedback.

            IMPORTANT: Use the TodoWrite tool to create a review checklist at the start, then mark each item as completed as you work through the review.

            Focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security implications
            - Test coverage
            - Documentation updates if needed

            Process:
            1. Create todo list with specific review tasks
            2. Mark each task as in_progress while working on it
            3. Mark each task as completed after providing feedback
            4. Provide constructive feedback with specific suggestions for improvement
            5. Use inline comments to highlight specific areas of concern
            6. Complete the review by marking all tasks as done

            After completing your review, update the todo list to show all tasks as completed.
          allowed_tools: |
            mcp__github__create_pending_pull_request_review
            mcp__github__add_pull_request_review_comment_to_pending_review
            mcp__github__submit_pending_pull_request_review
            mcp__github__get_pull_request_diff
            mcp__github__update_pull_request_review_comment
            TodoWrite
            TodoRead
            Bash(go test ./...)
            Bash(go mod tidy)
            Bash(go build ./...)
            Bash(go vet ./...)
            Bash(go fmt ./...)
